name: CI-compile

on:
  push:
  pull_request:

jobs:
  build-win:
    name: PMAP windows compilation
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild /p:PlatformToolset=v142 /p:Configuration=Release

      - uses: actions/upload-artifact@v3
        with:
          name: PMAP
          path: Release/*.exe

  # build-linux:
  #   name: PMAP linux compilation
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Build
  #       run: |
  #         cd PMAP-linux
  #         make
  #         tar -zcvf pmap.tar.gz pmap

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: PMAP
  #         path: linux/pmap.tar.gz
